language: node_js
sudo: false
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
  - "13"
  - "14"

cache:
  npm: false

stages:
  - name: test
    if: (type = push) OR (type = pull_request)
  - name: azure
    if: (type = push)
  - name: lint
    if: (type = push) OR (type = pull_request)
  - name: release
    if: (type = push) AND (branch = master)

services:
  - docker

before_install:
  - docker pull microsoft/mssql-server-linux
  - docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d microsoft/mssql-server-linux

  - mkdir ~/.tedious
  - >
    echo '{
      "config": {
        "server": "localhost",
        "authentication": {
          "type": "default",
          "options": {
            "userName": "sa",
            "password": "yourStrong(!)Password"
          }
        },
        "options": {
          "port": 1433,
          "database": "master",
          "trustServerCertificate": true
        }
      }
    }' > ~/.tedious/test-connection.json

before_script:
  - npm prune

script:
  - npx nyc --reporter=lcov npm run test && npx codecov
  - TEDIOUS_TDS_VERSION=7_4   npx nyc --reporter=lcov npm run test-integration && npx codecov
  - TEDIOUS_TDS_VERSION=7_3_B npx nyc --reporter=lcov npm run test-integration && npx codecov
  - TEDIOUS_TDS_VERSION=7_3_A npx nyc --reporter=lcov npm run test-integration && npx codecov
  - TEDIOUS_TDS_VERSION=7_2   npx nyc --reporter=lcov npm run test-integration && npx codecov
  - TEDIOUS_TDS_VERSION=7_1   npx nyc --reporter=lcov npm run test-integration && npx codecov

jobs:
  include:
    - stage: lint
      node_js: 8
      before_install: skip
      before_script: skip
      script:
        - npm run lint
        - commitlint-travis

    - stage: azure
      node_js: 8
      before_install:
      - mkdir ~/.tedious
      - >
        echo '{
          "config": {
            "server": "'${AZURE_SERVER}'",
            "authentication": {
              "type": "default",
              "options": {
                "userName": "'${AZURE_USERNAME}'",
                "password": "'${AZURE_PASS}'"
              }
            },
            "options": {
              "database": "tedious",
              "trustServerCertificate": true
            }
          }
        }' > ~/.tedious/test-connection.json
      before_script: skip
      script: npx nyc --reporter=lcov npm run test-integration && npx codecov

    - stage: azure
      node_js: 8
      before_install:
      - mkdir ~/.tedious
      - >
        echo '{
          "config": {
            "server": "'${AZURE_SERVER}'",
            "authentication": {
              "type": "azure-active-directory-password",
              "options": {
                "userName": "'${AZURE_AD_USER}'",
                "password": "'${AZURE_AD_PASS}'"
              }
            },
            "options": {
              "database": "tedious",
              "trustServerCertificate": true
            }
          }
        }' > ~/.tedious/test-connection.json
      before_script: skip
      script: npx nyc --reporter=lcov npm run test-integration && npx codecov

    - stage: azure
      node_js: 8
      before_install:
      - mkdir ~/.tedious
      - >
        echo '{
          "config": {
            "server": "'${AZURE_SERVER}'",
            "authentication": {
              "type": "azure-active-directory-access-token",
              "options": {
                "userName": "'${AZURE_AD_USER}'",
                "password": "'${AZURE_AD_PASS}'",
                "token": "undefined"
              }
            },
            "options": {
              "database": "test"
            }
          }
        }' > ~/.tedious/test-connection.json
      before_script: skip
      script: npm run test-integration

    - stage: release
      node_js: 12
      before_install: skip
      before_script: skip
      script: npm run semantic-release
